///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAppIcon = 'assets/images/app_icon.png';
  static const String imagesApplIcon = 'assets/images/appl_icon.svg';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesPageViewItem1BackgroundImage =
      'assets/images/page_view_item1_background_image.svg';
  static const String imagesPageViewItem1Image =
      'assets/images/page_view_item1_image.svg';
  static const String imagesPageViewItem2BackgroundImage =
      'assets/images/page_view_item2_background_image.svg';
  static const String imagesPageViewItem2Image =
      'assets/images/page_view_item2_image.svg';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesSplashBottom = 'assets/images/splash_bottom.svg';
}
