// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52BCiz_pe3-p78iO_vF5gzU2rVd_FXuc',
    appId: '1:717167524481:web:a10ba2972a060cdbd4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    authDomain: 'fruit-hub-11510.firebaseapp.com',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    measurementId: 'G-291RG7BLK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhhcKhzdv8y7S79ElpPdGe2k0ulqDOpr8',
    appId: '1:717167524481:android:c3d78058babbfc99d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZj4HVcPvExRdVAC6z-hs0aLvIYHAj4HA',
    appId: '1:717167524481:ios:1046c5c7657bb5bbd4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZj4HVcPvExRdVAC6z-hs0aLvIYHAj4HA',
    appId: '1:717167524481:ios:1046c5c7657bb5bbd4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52BCiz_pe3-p78iO_vF5gzU2rVd_FXuc',
    appId: '1:717167524481:web:94435c4036bece40d4eb80',
    messagingSenderId: '717167524481',
    projectId: 'fruit-hub-11510',
    authDomain: 'fruit-hub-11510.firebaseapp.com',
    storageBucket: 'fruit-hub-11510.firebasestorage.app',
    measurementId: 'G-E59T9XZCCP',
  );
}
